### ISSUE TITLE
Extra links in popup

### ISSUE THREAD

**Issue by jharej** [roelmann/moodle-theme_handlebar#4]
Is it possible to add any extra links to course management popup for teachers (for example report/progress/index.php?course=xy) ? I would insert it into extra links but the link includes parameter. Thanks for answer.

**Comment by roelmann** [comment]
There is no reason why a parameter would not work
eg as a test on my localhost the link (added via the Link popoups section of the handlebar settings page)
http://localhost/moodledev/course/view.php?id=5
takes you to course id=5, with the parameter id=5 on the url

**Comment by jharej** [comment]
I know that I can add url with parameter, but I can not add dynamic parameters. I gave you an example - report/progress/index.php?course=xy - xy is the number of current course that changes in every course.  Are there any place holders e.g. %courseid% or %userid% ?

**Comment by roelmann** [comment]
No, not in the settings. To do that you would need to goat into the
renderer and add them there as that would require php coding

**Comment by jharej** [comment]
... I suggest you add link report/progress/index.php?course=xy to the popup under Course Reports.
