### ISSUE TITLE
Error on editing topic name

### ISSUE THREAD

**Issue by jharej** [roelmann/moodle-theme_handlebar#5]
Hi, when editing the topic name directly from main course page I get an error when pressing enter

Error code: inplaceeditableerror
* line 465 of /lib/external/externallib.php: moodle_exception thrown
* line ? of unknownfile: call to core_external::update_inplace_editable()
* line 228 of /lib/externallib.php: call to call_user_func_array()
* line 59 of /lib/ajax/service.php: call to external_api::call_external_function()

Can you help?

**Comment by roelmann** [comment]
Cannot replicate
Error provided does not point to anything in handlebar
