### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by AndreLZGava** [roelmann/moodle-theme_handlebar#9]
Hello Roelman, how are you?

I was looking at some themes and I've found Edwiser RemUI, I really loved that dashboard with Tasks to complete, Course Stats, Course Analytics and recently activities. I would like to have that on handlebar, I know that your are a really bussy man. But do you have some tips to give? Do you think that for having this result I need to programm everithing, or do you know if there is something that I could use to achieve this quickly?

**Comment by roglos** [comment]
Sorry, I've never looked at RemUI, as it's commercial - so I have no idea whether its features could be easily ported to another theme.

**Comment by AndreLZGava** [comment]
Ok, thanks :)
